export const API_URL = 'https://31df-171-251-90-158.ngrok.io'
export const ACCESS_TOKEN_KEY = 'access_token'
export const CHAT_PREFIX = 'chat_'
export const CHAT_FILE = 'chat.json'
export const RATCHET_FILE = 'ratchet.json'
// export const AUTH_FILE = 'auth.json'
export const AUTH_FILE = 'auth1.json'
