export const API_URL = 'https://88d3-171-251-90-158.ngrok-free.app'
export const SOCKET_URL = 'wss://88d3-171-251-90-158.ngrok-free.app'
export const ACCESS_TOKEN_KEY = 'access_token'
export const CHAT_PREFIX = 'chat_'
export const CHAT_FILE = 'chat.json'
export const RATCHET_FILE = 'ratchet.json'
export const AUTH_FILE = 'auth.json'
// export const AUTH_FILE = 'auth2.json'
export const TEXT_TYPE = 'CHAT_TEXT' as const
